import { useEffect } from "react"

export default function Agreement () {
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])
  return (
    <div className="agreementpage">
      <h1>TERMS & CONDITIONS</h1>
      <h5>Effective Date: May 25, 2021</h5>
      <p>These Terms of Service, together with our Privacy Policy, govern your access to and use of the websites (the “DFG Sites” or the “Sites”) of Digital Finance  Group company. and those of its subsidiaries and affiliates, including (collectively, “DFG”, “we”, “our”, or “us”), and your use of any of the services provided through these Sites. These Terms of Service and any additional terms and conditions, policies, agreements and disclosures to which you have agreed are hereafter referred to collectively as the “Agreement”. Please read these Terms of Service carefully.</p>
      <p>Your use of a DFG Site is governed by the version of the Terms of Service in effect on the date of use. DFG may modify the Terms of Service at any time and without prior notice. By using and accessing any DFG Site, you acknowledge and agree to review the most current version of these Terms of Service prior to each such use. Your continued use of and access to any of the DFG Sites constitutes your acknowledgement of, and agreement to, the then current Terms of Service. Please also note that the terms and conditions of these Terms of Service are in addition to any other agreements between you and DFG and/or its affiliates and agents, including any customer agreements, and any other agreements that govern your use of products, services, content, tools, and information available on the DFG Sites.</p>
      <p>DFG reserves the right, in its sole discretion, without any obligation and without any notice requirement, to change, improve or correct the information, materials and descriptions on the DFG Sites and/or to suspend and/or deny access to any DFG Site for scheduled or unscheduled maintenance, upgrades, improvements or corrections. The information and materials on the DFG Site may contain typographical errors or inaccuracies. Any dated information is published as of its date only, and DFG does not undertake any obligation or responsibility to update or amend any such information. DFG may discontinue or change any product or service described in or offered on DFG Site at any time without prior notice. DFG further reserves the right, in its sole discretion, to block or otherwise discontinue your access and use of DFG Site at any time and for any reason. You agree that DFG and its subsidiaries and affiliates will not be liable to you or to any third party for any such modification, suspension or discontinuance.</p>

      <h1>AUTHORIZED USER</h1>
      <p>Some of our services, and certain pages of the DFG Site, are available only to clients or users who have been authorized by us to access those services and web pages. Such authorization may require completion of an accredited investor questionnaire and satisfactory background information screening.</p>
      <p>Unauthorized use of any DFG Site and/or our systems, including, but not limited to, unauthorized entry into and/or any attempted access of DFG’s systems and/or any restricted areas of any of the DFG Site, misuse or sharing of passwords or misuse of any other information, is strictly prohibited. You may not use any DFG Site in any manner that could damage, disable, overburden, or impair any DFG Site or service or interfere with any other party’s use and enjoyment of any DFG Site or service. You may not attempt to gain unauthorized access to any DFG Site or service, computer systems or networks connected to any DFG Site or service, through hacking, password mining or any other means. You may not screen-scrape, data scrape and/or use any automated means to acquire data and/or information from our Sites. You agree that you will not engage in any activities related to any DFG Site that are contrary to these Terms of Service and/or any applicable laws or regulations. You agree to notify us immediately in the event that you learn or suspect that the security of your password may have been compromised. You further agree that you are responsible for any unauthorized use of your password that is made before you have notified us and we have had a reasonable opportunity to act on that notice. We reserve the right to suspend or cancel your password, even without receiving such notice from you, if we suspect that it is being used in an unauthorized or fraudulent manner.</p>
      <p>Notwithstanding the above, you are responsible for monitoring your use of the DFG Sites and should promptly report any unauthorized or suspicious activity to us at contact@dfg.group</p>

      <h1>DISCLAIMER OF WARRANTY AND LIMITATION OF LIABILITY</h1>
      <p>THE INFORMATION, PRODUCTS AND SERVICES ON THE DFG SITES ARE PROVIDED ON A STRICTLY “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS. DFG DOES NOT PROVIDE ANY WARRANTIES (EITHER EXPRESS OR IMPLIED) WITH RESPECT TO THE INFORMATION AND/OR SERVICES PROVIDED ON ANY DFG SITE AND/OR YOUR USE OF ANY DFG SITE GENERALLY, FOR ANY PARTICULAR PURPOSE AND DFG EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. DFG WILL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE THAT COULD RESULT FROM INTERCEPTION BY THIRD PARTIES OF ANY INFORMATION OR SERVICES MADE AVAILABLE TO YOU VIA THIS WEBSITE. ALTHOUGH THE INFORMATION PROVIDED TO YOU ON THIS WEBSITE IS OBTAINED OR COMPILED FROM SOURCES WE BELIEVE TO BE RELIABLE, DFG CANNOT AND DOES NOT GUARANTEE THE ACCURACY, VALIDITY, TIMELINESS, OR COMPLETENESS OF ANY INFORMATION OR DATA MADE AVAILABLE TO YOU FOR ANY PARTICULAR PURPOSE. NEITHER DFG, NOR ANY OF ITS AFFILIATES, DIRECTORS, OFFICERS OR EMPLOYEES, NOR ANY THIRD PARTY PROVIDERS OF CONTENT, SOFTWARE AND/OR TECHNOLOGY (COLLECTIVELY, THE “DFG PARTIES”), WILL BE LIABLE OR HAVE ANY RESPONSIBILITY OF ANY KIND FOR ANY LOSS OR DAMAGE THAT YOU INCUR IN THE EVENT OF ANY FAILURE OR INTERRUPTION OF ANY DFG SITE, OR RESULTING FROM THE ACT OR OMISSION OF ANY OTHER PARTY INVOLVED IN MAKING ANY DFG SITE, THE DATA CONTAINED THEREIN OR THE PRODUCTS OR SERVICES OFFERED THEREBY AVAILABLE TO YOU, OR FROM ANY OTHER CAUSE RELATING TO YOUR ACCESS TO, INABILITY TO ACCESS, OR USE OF ANY DFG SITE OR THE MATERIALS CONTAINED THEREIN, WHETHER OR NOT THE CIRCUMSTANCES GIVING RISE TO SUCH CAUSE MAY HAVE BEEN WITHIN THE CONTROL OF DFG OR OF ANY VENDOR PROVIDING SOFTWARE OR SERVICES.</p>
      <p>IN NO EVENT WILL DFG OR ANY SUCH PARTIES BE LIABLE TO YOU, WHETHER IN CONTRACT OR TORT, FOR ANY DIRECT, SPECIAL, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR ANY OTHER DAMAGES OF ANY KIND EVEN IF DFG OR ANY OTHER SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY THEREOF. THIS LIMITATION ON LIABILITY INCLUDES, BUT IS NOT LIMITED TO, THE TRANSMISSION OF ANY VIRUSES WHICH MAY INFECT A USER’S EQUIPMENT, FAILURE OF MECHANICAL OR ELECTRONIC EQUIPMENT OR COMMUNICATION LINES, TELEPHONE OR OTHER INTERCONNECT PROBLEMS (E.G., YOU CANNOT ACCESS YOUR INTERNET SERVICE PROVIDER), UNAUTHORIZED ACCESS, THEFT, OPERATOR ERRORS, STRIKES OR OTHER LABOR PROBLEMS OR ANY FORCE MAJEURE. DFG CANNOT AND DOES NOT GUARANTEE CONTINUOUS, UNINTERRUPTED OR SECURE ACCESS T</p>

      <h1>PROPRIETARY RIGHTS</h1>
      <p>THE INFORMATION, PRODUCTS AND SERVICES ON THE DFG SITES ARE PROVIDED ON A STRICTLY “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS. DFG DOES NOT PROVIDE ANY WARRANTIES (EITHER EXPRESS OR IMPLIED) WITH RESPECT TO THE INFORMATION AND/OR SERVICES PROVIDED ON ANY DFG SITE AND/OR YOUR USE OF ANY DFG SITE GENERALLY, FOR ANY PARTICULAR PURPOSE AND DFG EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. DFG WILL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE THAT COULD RESULT FROM INTERCEPTION BY THIRD PARTIES OF ANY INFORMATION OR SERVICES MADE AVAILABLE TO YOU VIA THIS WEBSITE. ALTHOUGH THE INFORMATION PROVIDED TO YOU ON THIS WEBSITE IS OBTAINED OR COMPILED FROM SOURCES WE BELIEVE TO BE RELIABLE, DFG CANNOT AND DOES NOT GUARANTEE THE ACCURACY, VALIDITY, TIMELINESS, OR COMPLETENESS OF ANY INFORMATION OR DATA MADE AVAILABLE TO YOU FOR ANY PARTICULAR PURPOSE. NEITHER DFG, NOR ANY OF ITS AFFILIATES, DIRECTORS, OFFICERS OR EMPLOYEES, NOR ANY THIRD PARTY PROVIDERS OF CONTENT, SOFTWARE AND/OR TECHNOLOGY (COLLECTIVELY, THE “DFG PARTIES”), WILL BE LIABLE OR HAVE ANY RESPONSIBILITY OF ANY KIND FOR ANY LOSS OR DAMAGE THAT YOU INCUR IN THE EVENT OF ANY FAILURE OR INTERRUPTION OF ANY DFG SITE, OR RESULTING FROM THE ACT OR OMISSION OF ANY OTHER PARTY INVOLVED IN MAKING ANY DFG SITE, THE DATA CONTAINED THEREIN OR THE PRODUCTS OR SERVICES OFFERED THEREBY AVAILABLE TO YOU, OR FROM ANY OTHER CAUSE RELATING TO YOUR ACCESS TO, INABILITY TO ACCESS, OR USE OF ANY DFG SITE OR THE MATERIALS CONTAINED THEREIN, WHETHER OR NOT THE CIRCUMSTANCES GIVING RISE TO SUCH CAUSE MAY HAVE BEEN WITHIN THE CONTROL OF DFG OR OF ANY VENDOR PROVIDING SOFTWARE OR SERVICES.</p>
      <p>IN NO EVENT WILL DFG OR ANY SUCH PARTIES BE LIABLE TO YOU, WHETHER IN CONTRACT OR TORT, FOR ANY DIRECT, SPECIAL, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR ANY OTHER DAMAGES OF ANY KIND EVEN IF DFG OR ANY OTHER SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY THEREOF. THIS LIMITATION ON LIABILITY INCLUDES, BUT IS NOT LIMITED TO, THE TRANSMISSION OF ANY VIRUSES WHICH MAY INFECT A USER’S EQUIPMENT, FAILURE OF MECHANICAL OR ELECTRONIC EQUIPMENT OR COMMUNICATION LINES, TELEPHONE OR OTHER INTERCONNECT PROBLEMS (E.G., YOU CANNOT ACCESS YOUR INTERNET SERVICE PROVIDER), UNAUTHORIZED ACCESS, THEFT, OPERATOR ERRORS, STRIKES OR OTHER LABOR PROBLEMS OR ANY FORCE MAJEURE. DFG CANNOT AND DOES NOT GUARANTEE CONTINUOUS, UNINTERRUPTED OR SECURE ACCESS T</p>

      <h3>Contact Us</h3>
      <h4>Email: <a href="mailto:contact@dfg.group">contact@dfg.group</a></h4>

      <div className="page">
        <li className="active">1</li>
        <li>2</li>
      </div>
    </div>
  )
}