import { useEffect } from "react"

export default function Agreement () {
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])
  
  return (
    <div className="agreementpage">
      <h1>TERMS & CONDITIONS</h1>
      <h5>Effective Date: May 25, 2021</h5>
      <p>These Terms of Service, together with our Privacy Policy, govern your access to and use of the websites (the “DFG Sites” or the “Sites”) of Digital Finance  Group company. and those of its subsidiaries and affiliates, including (collectively, “DFG”, “we”, “our”, or “us”), and your use of any of the services provided through these Sites. These Terms of Service and any additional terms and conditions, policies, agreements and disclosures to which you have agreed are hereafter referred to collectively as the “Agreement”. Please read these Terms of Service carefully.</p>
      <p>Your use of a DFG Site is governed by the version of the Terms of Service in effect on the date of use. DFG may modify the Terms of Service at any time and without prior notice. By using and accessing any DFG Site, you acknowledge and agree to review the most current version of these Terms of Service prior to each such use. Your continued use of and access to any of the DFG Sites constitutes your acknowledgement of, and agreement to, the then current Terms of Service. Please also note that the terms and conditions of these Terms of Service are in addition to any other agreements between you and DFG and/or its affiliates and agents, including any customer agreements, and any other agreements that govern your use of products, services, content, tools, and information available on the DFG Sites.</p>
      <p>DFG reserves the right, in its sole discretion, without any obligation and without any notice requirement, to change, improve or correct the information, materials and descriptions on the DFG Sites and/or to suspend and/or deny access to any DFG Site for scheduled or unscheduled maintenance, upgrades, improvements or corrections. The information and materials on the DFG Site may contain typographical errors or inaccuracies. Any dated information is published as of its date only, and DFG does not undertake any obligation or responsibility to update or amend any such information. DFG may discontinue or change any product or service described in or offered on DFG Site at any time without prior notice. DFG further reserves the right, in its sole discretion, to block or otherwise discontinue your access and use of DFG Site at any time and for any reason. You agree that DFG and its subsidiaries and affiliates will not be liable to you or to any third party for any such modification, suspension or discontinuance.</p>

      <h1>AUTHORIZED USER</h1>
      <p>Some of our services, and certain pages of the DFG Site, are available only to clients or users who have been authorized by us to access those services and web pages. Such authorization may require completion of an accredited investor questionnaire and satisfactory background information screening.</p>
      <p>Unauthorized use of any DFG Site and/or our systems, including, but not limited to, unauthorized entry into and/or any attempted access of DFG’s systems and/or any restricted areas of any of the DFG Site, misuse or sharing of passwords or misuse of any other information, is strictly prohibited. You may not use any DFG Site in any manner that could damage, disable, overburden, or impair any DFG Site or service or interfere with any other party’s use and enjoyment of any DFG Site or service. You may not attempt to gain unauthorized access to any DFG Site or service, computer systems or networks connected to any DFG Site or service, through hacking, password mining or any other means. You may not screen-scrape, data scrape and/or use any automated means to acquire data and/or information from our Sites. You agree that you will not engage in any activities related to any DFG Site that are contrary to these Terms of Service and/or any applicable laws or regulations. You agree to notify us immediately in the event that you learn or suspect that the security of your password may have been compromised. You further agree that you are responsible for any unauthorized use of your password that is made before you have notified us and we have had a reasonable opportunity to act on that notice. We reserve the right to suspend or cancel your password, even without receiving such notice from you, if we suspect that it is being used in an unauthorized or fraudulent manner.</p>
      <p>Notwithstanding the above, you are responsible for monitoring your use of the DFG Sites and should promptly report any unauthorized or suspicious activity to us at contact@dfg.group</p>

      <h1>DISCLAIMER OF WARRANTY AND LIMITATION OF LIABILITY</h1>
      <p>THE INFORMATION, PRODUCTS AND SERVICES ON THE DFG SITES ARE PROVIDED ON A STRICTLY “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS. DFG DOES NOT PROVIDE ANY WARRANTIES (EITHER EXPRESS OR IMPLIED) WITH RESPECT TO THE INFORMATION AND/OR SERVICES PROVIDED ON ANY DFG SITE AND/OR YOUR USE OF ANY DFG SITE GENERALLY, FOR ANY PARTICULAR PURPOSE AND DFG EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. DFG WILL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE THAT COULD RESULT FROM INTERCEPTION BY THIRD PARTIES OF ANY INFORMATION OR SERVICES MADE AVAILABLE TO YOU VIA THIS WEBSITE. ALTHOUGH THE INFORMATION PROVIDED TO YOU ON THIS WEBSITE IS OBTAINED OR COMPILED FROM SOURCES WE BELIEVE TO BE RELIABLE, DFG CANNOT AND DOES NOT GUARANTEE THE ACCURACY, VALIDITY, TIMELINESS, OR COMPLETENESS OF ANY INFORMATION OR DATA MADE AVAILABLE TO YOU FOR ANY PARTICULAR PURPOSE. NEITHER DFG, NOR ANY OF ITS AFFILIATES, DIRECTORS, OFFICERS OR EMPLOYEES, NOR ANY THIRD PARTY PROVIDERS OF CONTENT, SOFTWARE AND/OR TECHNOLOGY (COLLECTIVELY, THE “DFG PARTIES”), WILL BE LIABLE OR HAVE ANY RESPONSIBILITY OF ANY KIND FOR ANY LOSS OR DAMAGE THAT YOU INCUR IN THE EVENT OF ANY FAILURE OR INTERRUPTION OF ANY DFG SITE, OR RESULTING FROM THE ACT OR OMISSION OF ANY OTHER PARTY INVOLVED IN MAKING ANY DFG SITE, THE DATA CONTAINED THEREIN OR THE PRODUCTS OR SERVICES OFFERED THEREBY AVAILABLE TO YOU, OR FROM ANY OTHER CAUSE RELATING TO YOUR ACCESS TO, INABILITY TO ACCESS, OR USE OF ANY DFG SITE OR THE MATERIALS CONTAINED THEREIN, WHETHER OR NOT THE CIRCUMSTANCES GIVING RISE TO SUCH CAUSE MAY HAVE BEEN WITHIN THE CONTROL OF DFG OR OF ANY VENDOR PROVIDING SOFTWARE OR SERVICES.</p>
      <p>IN NO EVENT WILL DFG OR ANY SUCH PARTIES BE LIABLE TO YOU, WHETHER IN CONTRACT OR TORT, FOR ANY DIRECT, SPECIAL, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR ANY OTHER DAMAGES OF ANY KIND EVEN IF DFG OR ANY OTHER SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY THEREOF. THIS LIMITATION ON LIABILITY INCLUDES, BUT IS NOT LIMITED TO, THE TRANSMISSION OF ANY VIRUSES WHICH MAY INFECT A USER’S EQUIPMENT, FAILURE OF MECHANICAL OR ELECTRONIC EQUIPMENT OR COMMUNICATION LINES, TELEPHONE OR OTHER INTERCONNECT PROBLEMS (E.G., YOU CANNOT ACCESS YOUR INTERNET SERVICE PROVIDER), UNAUTHORIZED ACCESS, THEFT, OPERATOR ERRORS, STRIKES OR OTHER LABOR PROBLEMS OR ANY FORCE MAJEURE. DFG CANNOT AND DOES NOT GUARANTEE CONTINUOUS, UNINTERRUPTED OR SECURE ACCESS T</p>

      <h1>PROPRIETARY RIGHTS</h1>
      <p>All right, title and interest in the DFG Sites and all content contained herein is the exclusive property of DFG, except as otherwise stated. Unless otherwise specified, the DFG Sites are for your personal and non-commercial use only. You may print, copy and download limited amounts of information and content from the DFG Sites; provided that it is solely for your personal use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, frame, create derivative works from, transfer, or otherwise use in any other way for commercial or public purposes in whole or in part any information, software, products or services obtained from any DFG Sites, except for the purposes expressly provided herein, without DFG’s’ prior written approval. If you copy or download any information or software from a DFG Site, you agree that you will not remove or obscure any copyright or other notices or legends contained in any such information.</p>
      <p>DFG, the DFG logo, and other DFG trademarks and service marks referenced herein are trademarks and service marks of DFG. The names of other companies and third-party products or services mentioned herein may be the trademarks or service marks of their respective owners. You are prohibited from using any marks for any purpose including, but not limited to use as metatags on other pages or sites on the Internet without the written permission of DFG or the applicable third party rights holder.</p>

      <h1>USE OF LINKS</h1>
      <p>The DFG Sites may contain links to third party websites and/or services (each, a “Third Party Site”). These links are provided only as a convenience. The inclusion of any link is not and does not imply an affiliation, sponsorship, endorsement, approval, investigation, verification or monitoring by DFG of any information contained in any Third Party Site. In no event shall DFG be responsible for the information contained on any Third Party Site and/or your use of or inability to use such site. You should also be aware that the terms and conditions and privacy policy of each Third Party Site will be different from those applicable to your use of the DFG Sites. You should contact the operator of the applicable Third Party Site for any information regarding that site’s terms and conditions and/or privacy policy.</p>

      <h1>THIRD PARTY CONTENT</h1>
      <p>Certain portions of the DFG Sites may contain unedited or third party content, including, without limitation, User Submitted Content. All User Submitted Content and all other postings, messages, text, images, links to third-party websites or other materials published on or otherwise made available by parties other than DFG (such content, the “Third Party Content”) are the sole responsibility of the person(s) who originated such Third Party Content and DFG may not monitor and does not control such Third Party Content, though DFG reserves the right at all times (but will not have an obligation) to remove any Third Party Content. By using this Third Party Content, you agree to not rely on the Third Party Content and understand that you may be exposed to Third Party Content that is, without limitation, inaccurate, inappropriate, misleading, unlawful, offensive or otherwise objectionable, and that DFG makes no representations or warranties regarding the Third Party Content and is not responsible or liable in any manner for the Third Party Content or the conduct, whether online or offline, of any user. Your use of such Third Party Content may be subject to the terms of service or user agreement of such Third Party Content provider.</p>

      <h1>CLAIMS OF COPYRIGHT INFRINGEMENT</h1>
      <p>Copyright Complaints: DFG respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, you should notify DFG in accordance with the procedure set forth below.</p>
      <p>DFG will process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act (“DMCA”) and other applicable intellectual property laws with respect to any alleged or actual infringement. A notification of claimed copyright infringement should be sent to: contact@dfg.group</p>

      <p>To be effective, the notification must be in writing and contain the following information:</p>
      <p>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;
      a description of the copyrighted work or other intellectual property that you claim has been infringed;
      a description of where the material that you claim is infringing is located on the DFG Site, with enough detail that we may find it on the DFG Site;
      your address, telephone number, and email address;
      a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law; and
      a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.
      </p>

      <h1>INDEMNITY AND RELEASE</h1>
      <p>You agree to release, indemnify and hold DFG harmless from any from any and all losses, damages, expenses, including reasonable attorneys’ fees, rights, claims, actions of any kind and injury (including death) arising out of or relating to your use of the DFG Sites. If you are a California resident, you waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.” If you are a resident of another jurisdiction, you waive any comparable statute or doctrine.</p>
      
      <h1>CHOICE OF LAW</h1>
      <p>The Agreement shall be governed by and construed and enforced in accordance with the laws of the State of Cayman Islands, without regard to conflicts of laws provisions. Unless otherwise agreed in writing by you and us, any dispute arising out of or relating to the Agreement, or the breach hereof, shall be finally resolved by arbitration administered by the Cayman Islands Arbitration Association under its Commercial Arbitration Rules, or such arbitration body as required by law, rule or regulation, and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction. The arbitration will be conducted in the English language before a single arbitrator in the City of Cayman Islands.Such arbitration must be commenced within one (1) year after the claim or cause of action arises. If for any reason any provision of this Agreement, or a portion thereof, shall be unenforceable, that provision shall be enforced to the maximum extent permissible so as to effect the intent of this Agreement, and the remainder of this Agreement shall continue in full force and effect. This Agreement constitutes the entire agreement between us and you with respect to this site and it supersedes all prior or contemporaneous communications, agreements and understandings between DFG and you with respect to the subject matter hereof. A printed version of this Agreement shall be admissible in judicial or administrative proceedings.</p>

      <h3>Contact Us</h3>
      <h4>Email: <a href="mailto:contact@dfg.group">contact@dfg.group</a></h4>

    </div>
  )
}